version: 2

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/source/conf.py

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "mambaforge-latest"

conda:
  environment: ci/docs.yml

formats: []
